# Site settings
title: Silico-Paleontology
email: mcphee@morris.umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://silico-paleontology.github.io" # the base hostname & protocol for your site
twitter_username: NicMcPhee
github_username:  Silico-Paleontology

timezone: America/Chicago

# Build settings
markdown: kramdown
